/// Flutter icons Hackmate
/// Copyright (C) 2024 by original authors @ fontello.com
/// This font was generated by Fontello.
///
/// Font license info
///
/// ## Font Awesome
///
///    Copyright (C) 2016 by Dave Gandy
///
///    Author:    Dave Gandy
///    License:   SIL ()
///    Homepage:  http://fortawesome.github.com/Font-Awesome/
///
/// ## Iconic
///
///    Copyright (C) 2012 by P.J. Onori
///
///    Author:    P.J. Onori
///    License:   SIL (http://scripts.sil.org/OFL)
///    Homepage:  http://somerandomdude.com/work/iconic/
///
/// ## Typicons
///
///    (c) Stephen Hutchings 2012
///
///    Author:    Stephen Hutchings
///    License:   SIL (http://scripts.sil.org/OFL)
///    Homepage:  http://typicons.com/
///
/// ## MFG Labs
///
///    Copyright (C) 2012 by Daniel Bruce
///
///    Author:    MFG Labs
///    License:   SIL (http://scripts.sil.org/OFL)
///    Homepage:  http://www.mfglabs.com/
///
/// ## Fontelico
///
///    Copyright (C) 2012 by Fontello project
///
///    Author:    Crowdsourced, for Fontello project
///    License:   SIL (http://scripts.sil.org/OFL)
///    Homepage:  http://fontello.com
library;

import 'package:flutter/widgets.dart';

class HackmateIcons {
  HackmateIcons._();

  static const _kFontFam = 'Hackmate';
  static const String? _kFontPkg = null;

  static const IconData twitter =
      IconData(61593, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(61595, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(61856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(62220, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(59394, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat =
      IconData(59395, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(59396, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(59397, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(59398, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipe =
      IconData(59392, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(61616, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reject =
      IconData(59400, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love =
      IconData(59393, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crownfilled =
      IconData(59460, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
